all:
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_become: true
    ansible_ssh_private_key_file: /home/mharcej/.ssh/ansible/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

    ssl_enabled: true
    delete_generation_dir: false
    # ssl_provided_keystore_and_truststore: true
    # ssl_keystore_filepath: "/home/mharcej/keystores/{{inventory_hostname}}-keystore.jks"
    # ssl_keystore_key_password: secret
    # ssl_keystore_store_password: secret
    # ssl_truststore_filepath: "/home/mharcej/github/confluent-platform-security-tools/truststore/kafka.truststore.jks"
    # ssl_truststore_password: secret
    kafka_broker_custom_properties:
      ssl.endpoint.identification.algorithm: ""
    sasl_protocol: plain
    sasl_plain_users:
      admin:
        principal: 'admin'
        password: 'admin-secret'
      client:
        principal: 'client'
        password: 'client-secret'
    kafka_broker_custom_listeners:
      SASL_SSL:
        name: "SASL_SSL"
        port: 9093
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: plain

zookeeper:
  hosts:
    zookeeper:
      ansible_ssh_host: 10.61.191.59
  vars:
    # zookeeper_custom_java_args: "-Djava.security.auth.login.config=etc/kafka/zookeeper_jaas.conf"
    # zookeeper_client_authentication_type: digest

kafka_broker:
  vars:
    kafka_controller_metrics_reporter_enabled: true
    kafka_broker_metrics_reporter_enabled: true
  hosts:
    broker1:
      ansible_ssh_host: 10.61.191.42
    broker2:
      ansible_ssh_host: 10.61.191.137
    broker3:
      ansible_ssh_host: 10.61.191.243

# schema_registry:
#   hosts:
#     10.61.191.44:

# kafka_connect:
#   hosts:
#     10.61.191.44:
#       vars:
#         kafka_connect_confluent_hub_plugins:
#           - confluentinc/kafka-connect-datagen:0.4.0

# docker:
#   hosts:
#     10.61.191.130:
