---
version: '2'
services:

    control-center:
      image: confluentinc/cp-enterprise-control-center:7.5.2
      hostname: control-center
      container_name: control-center
      ports:
        - "9021:9021"
      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: 'Kafka-cp1:9092,Kafka-cp2:9092,Kafka-cp3:9092'
  #      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
  #      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
  #      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
  #      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
  #      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
        CONTROL_CENTER_REPLICATION_FACTOR: 3
        CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 9
        CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 9
        CONFLUENT_METRICS_TOPIC_REPLICATION: 3
        PORT: 9021