version: '2'

services:
  # https://github.com/yahoo/kafka-manager
  kafka-manager:
    image: deltaprojects/kafka-manager
    network_mode: host
    environment:
      ZK_HOSTS: "Kafka1:2181,Kafka2:2181,Kafka3:2181"
      APPLICATION_SECRET: change_me_please
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: password
    restart: always
