---
- name: Configure kafka
  hosts: kafka, kafka-cp
  become: true

  pre_tasks:
    - name: Create the kafka directory
      file:
        path: /data/kafka
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Increase hard file handle limits
      pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: nofile
        value: 100000
    
    - name: Increase soft file handle limits
      pam_limits:
        domain: '*'
        limit_type: soft
        limit_item: nofile
        value: 100000

  
  tasks:
    - name: Copy server.properties template
      template:
        src: templates/kafka/server.properties.j2
        dest: "{{ kafka_dir }}/config/server.properties"

    - name: Create /etc/systemd/system/kafka
      template:
        src: templates/kafka/kafka.service.j2
        dest: /etc/systemd/system/kafka.service
        owner: root
        group: root
        mode: '0755'  

    - name: Update Systemctl
      systemd:  
        daemon_reload: true

  post_tasks:
    - name: Reboot the machine
      reboot:
        reboot_timeout: 3600
      tags: reboot