---
- name: Configure Zookeeper Quorum
  hosts: kafka, kafka-cp
  become: true

  # pre_tasks:
  #   - name: Stop Zookeeper if running
  #     service:
  #       name: zookeeper
  #       state: stopped
    
  tasks:
    - name: Create the data directory
      file:
        path: /data/zookeeper
        state: directory
        owner: ansible
        group: ansible

    - name: Create the myid file
      file:
        path: /data/zookeeper/myid
        state: touch
        owner: ansible
        group: ansible
    
    - name: Add the zookeeper id
      lineinfile:
        path: /data/zookeeper/myid
        insertbefore: BOF
        line: "{{ zookeeper_id }}"
    
    - name: Create the config directory
      file:
        path: "{{ kafka_dir }}/config"
        state: directory
    
    - name: Copy the zookeeper.properties template
      template:
        src: templates/zookeeper/zookeeper.properties.j2
        dest: "{{ kafka_dir }}/config/zookeeper.properties"

    - name: Create /etc/systemd/system/zookeeper
      template:
        src: templates/zookeeper/zookeeper.service.j2
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: '0755'  

    - name: Update Systemctl
      systemd:  
        daemon_reload: true
    
  post_tasks:
    - name: Start the Zookeeper service
      service:
        name: zookeeper
        state: started
      tags: start