---
- name: Install Zookeeper
  hosts: all
  become: true
  vars:

  pre_tasks:
    - name: Install dependencies
      apt:
        name:
          - wget
          - ca-certificates
          - zip
          - net-tools
          - vim
          - nano
          - tar
          - netcat
          - default-jdk
        state: present
        update_cache: true

    - name: Check java version
      command: java --version
      register: output

    - name: Print java version
      debug:
        msg: "{{ output.stdout }}"

    - name: Disable RAM swap
      sysctl:
        name: vm.swappiness
        value: '1'
        state: present
      tags: 
        - disable_swap
        - always
    
  tasks:
    - name: Download Zookeeper and Kafka
      get_url:
        url: "https://downloads.apache.org/kafka/3.6.0/{{ kafka_version }}.tgz"
        dest: "/home/{{ ansible_user }}"
    
    - name: Unarchive the file
      unarchive:
        src: "/home/{{ ansible_user }}/{{ kafka_version }}.tgz"
        dest: "/home/{{ ansible_user }}"
        remote_src: true
    
    - name: "Move kafka to {{ kafka_dir }}"
      copy:
        src: "/home/{{ ansible_user }}/{{ kafka_version }}/"
        dest: "{{ kafka_dir }}"
        remote_src: true

  post_tasks:
    - name: "Add {{ kafka_dir }} to PATH"
      copy:
        dest: /etc/profile.d/kafka-path.sh
        content: 'PATH=$PATH:{{ kafka_dir }}/bin'
        mode: '0644'